// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a key is stored. Local only — no network, no key returned.
 */
async hasFalApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates a pasted key and stores it in the keychain if it works.
 * 
 * A key that fails validation is not stored, so a saved key is always one that
 * worked at least once. Saving over an existing key replaces it.
 */
async saveFalApiKey(key: string) : Promise<Result<KeyCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_fal_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-validates the stored key against the live API.
 */
async checkFalApiKey() : Promise<Result<KeyCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the stored key. Succeeds when there was nothing to remove.
 */
async clearFalApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Submits one generation and returns as soon as it is on the books.
 * 
 * The generation id is minted by the caller and passed in rather than
 * returned: the file is named after it, so the manifest and the folder agree
 * without anyone having to reconcile them afterwards.
 * 
 * `recipe` is the draft frozen at submit, stored opaquely and handed back when
 * the job is collected. It travels with the job because a resumed job lands
 * in a session whose draft may say something else entirely, and a generation
 * has to carry the recipe that produced it (PRD §1).
 * 
 * `pinned_seed` is the seed the recipe asked for, if it asked for one
 * (PRD §4.3). Passing it is what makes "same seed, one changed fragment" a
 * real comparison rather than an approximate one.
 */
async generateImage(request: StartRequest) : Promise<Result<SubmittedJob, GenerationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_image", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What this project still has in flight — including anything a previous run
 * of the app submitted.
 */
async activeJobs(projectId: string) : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("active_jobs", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Finished jobs whose candidate is not in the manifest yet.
 */
async finishedJobs(projectId: string) : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finished_jobs", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the whole library has in flight (ADR 0002).
 * 
 * The overview's cards cover projects nobody has open, and a card that could
 * only see the open project's work would mark the wrong projects as busy.
 */
async activeJobsEverywhere() : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("active_jobs_everywhere") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every finished job across the library, waiting to be written into whichever
 * manifest it belongs to.
 * 
 * Collection stopped being bound to the open project (ADR 0002): a result is
 * paid for whether or not anyone is looking at it, and the point of a front
 * door is watching work arrive.
 */
async finishedJobsEverywhere() : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finished_jobs_everywhere") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Takes a collected job off the books.
 * 
 * Called after the manifest has been written, never before: the row is the
 * only record that a paid result exists, so dropping it first would turn a
 * badly timed crash into a lost generation.
 */
async claimJob(requestId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_job", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops a running job.
 * 
 * Cancelling stops us watching and asks fal to stop working. It does **not**
 * promise a refund — a job far enough along is charged regardless (PRD §3.3),
 * and the copy around this button says so.
 */
async cancelJob(requestId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_job", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every charge fal recorded between two moments, in milliseconds since the
 * epoch — the window clamped to fal's 90 days on the way past.
 * 
 * One call for the whole library rather than one per project: the endpoint is
 * keyed by request id and knows nothing about our folders, so a per-project
 * sweep would be the same pages fetched N times.
 * 
 * Fails rather than answering emptily when there is no key, which is the same
 * thing an offline machine or a refused request does. That distinction is the
 * caller's whole safety net: a pass that did not read the window must not move
 * the watermark over it.
 */
async falBillingEvents(startMs: number, endMs: number) : Promise<Result<BillingCharge[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fal_billing_events", { startMs, endMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The project list — the overview's grid of cards (#55).
 * 
 * Reconciles first, so a deleted database, a project restored from a backup
 * and a folder copied in by hand all show up as simply "the projects".
 */
async listProjects() : Promise<Result<ProjectSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One project's manifest, as it is on disk.
 */
async loadProject(projectId: string) : Promise<Result<ProjectRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a manifest and updates its index row.
 * 
 * Also the create path: a project is created by saving one. There is no
 * separate "new project" on disk, so creation and every later edit take the
 * identical code path — including the atomic write.
 */
async saveProject(manifest: JsonValue) : Promise<Result<ProjectSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { manifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a project and everything in its folder.
 * 
 * The one thing here that removes anything without being asked twice, which
 * is why the caller is expected to have asked. PRD §10.3 keeps *candidates*,
 * not projects someone has explicitly thrown away.
 */
async deleteProject(projectId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the project costs on disk, and how much of it nothing points at
 * (PRD §10.3).
 */
async projectUsage(projectId: string) : Promise<Result<ProjectUsage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_usage", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the unreferenced assets, and only those. Deliberate, never
 * automatic — nothing is discarded until someone asks (PRD §10.3).
 */
async cleanupUnusedAssets(projectId: string) : Promise<Result<CleanupOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_unused_assets", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies an image the user already has into a project (#27).
 * 
 * The convergence point of the slice: what comes back is a file in the
 * project's `assets` folder named after its generation — the same artefact a
 * finished job produces — so nothing downstream has to know the pixels were
 * not generated.
 * 
 * Fails with a *reason* rather than a sentence, so the refusal can be said in
 * the user's own language (PRD §10.4), and fails before anything is recorded
 * so an unusable file never becomes a candidate.
 */
async importSourceImage(projectId: string, generationId: string, sourcePath: string) : Promise<Result<ImportedImage, ImportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_source_image", { projectId, generationId, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Files the poster the webview drew for a clip (ADR 0004).
 * 
 * The one thumbnail Rust cannot make for itself. Capturing a frame needs a
 * decoder, and the webview already has one — the alternative is an
 * ffmpeg-class dependency for a single frame.
 * 
 * The bytes cross as bytes, the way a baked frame does (`write_baked_frame`),
 * and they are decoded and re-encoded before being filed: a card picture that
 * is not an image would survive every rebuild, since the file being there is
 * what tells the next listing there is nothing to do.
 */
async saveVideoPoster(projectId: string, asset: string, poster: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_video_poster", { projectId, asset, poster }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every style preset the user has saved, in a stable order.
 * 
 * Whether each document *is* a preset is not asked here — the frontend runs it
 * through `readPresetLibrary`, which fails loudly on a malformed one (PRD §6).
 */
async userPresetsList() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_presets_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes one style preset, by id — creating it, or updating one of the user's
 * own in place. Atomically, so an interrupted save cannot leave a half-written
 * fork.
 */
async userPresetSave(id: string, document: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_preset_save", { id, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes one style preset. Deleting one that is already gone is not an error.
 */
async userPresetDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_preset_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every motion preset the user has saved, in a stable order.
 * 
 * A second library, independent of the style one (#29): look and movement are
 * orthogonal, so the same id may exist in both and mean two different things.
 */
async motionPresetsList() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("motion_presets_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes one motion preset, by id — creating it, or updating one of the user's
 * own in place.
 */
async motionPresetSave(id: string, document: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("motion_preset_save", { id, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes one motion preset. Deleting one that is already gone is not an error.
 */
async motionPresetDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("motion_preset_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every source preset the user has saved, in a stable order.
 * 
 * A third library, independent of the other two (#47). A source preset is a
 * whole scene where a style preset is a transform applied to somebody else's
 * composition — so the same id may exist in both and mean two different things.
 */
async sourcePresetsList() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("source_presets_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes one source preset, by id — creating it, or updating one of the user's
 * own in place.
 */
async sourcePresetSave(id: string, document: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("source_preset_save", { id, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes one source preset. Deleting one that is already gone is not an error.
 */
async sourcePresetDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("source_preset_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every effects look the user has saved, in a stable order.
 * 
 * A fourth library, independent of the other three (#36). A look is not a
 * prompt at all — it seeds no stage and composes no text — so nothing about it
 * can shadow or be shadowed by a preset that shares its id.
 */
async effectsLooksList() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("effects_looks_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes one look, by id — creating it, or updating one of the user's own.
 */
async effectsLookSave(id: string, document: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("effects_look_save", { id, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes one look. Deleting one that is already gone is not an error.
 */
async effectsLookDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("effects_look_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every palette the user has saved, in a stable order.
 * 
 * A fourth library over the same store (#49), and the one that is not a preset
 * library: a palette is six colours a project copies in rather than a seed for
 * a stage. What it shares is the storage, so it shares the store and nothing
 * else — including the folder, which is `palettes/` rather than a nested one.
 */
async userPalettesList() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_palettes_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes one palette, by id — creating it, or updating one of the user's own
 * in place.
 */
async userPaletteSave(id: string, document: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_palette_save", { id, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes one palette. Deleting one that is already gone is not an error.
 */
async userPaletteDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_palette_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One still, treated, as PNG bytes.
 * 
 * Runs on a blocking thread: #52 measured error diffusion at ~81 ms for a
 * full-resolution frame, which is fine for a debounced preview and is not fine
 * on an async runtime thread.
 * 
 * A PNG rather than raw pixels, because a 2560×1440 frame is ~11 MB raw and
 * dithered output compresses hard — the encode pays for itself several times
 * over on the way through IPC.
 */
async renderTreatedStill(projectId: string, generationId: string, effect: CpuEffect) : Promise<Result<number[], EffectError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_treated_still", { projectId, generationId, effect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether there is an ffmpeg, from the answer taken at startup.
 * 
 * Cheap and cached, because the export panel asks on every render and the
 * answer changes about once per `brew install`.
 * 
 * Still on a blocking thread, for the case the cache is cold: a probe spawns a
 * process per candidate path, and a stalled binary on the `PATH` would
 * otherwise stall the runtime rather than one thread of it.
 */
async ffmpegStatus() : Promise<Result<FfmpegStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ffmpeg_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Looks again — the panel's re-check button, so installing ffmpeg while the
 * app is open does not need a relaunch.
 * 
 * Always spawns processes, so always off the runtime.
 */
async recheckFfmpeg() : Promise<Result<FfmpegStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recheck_ffmpeg") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Encodes one candidate into the files a landing page can use.
 * 
 * Runs on a blocking thread: a WebM of a ten-second hero is tens of seconds of
 * CPU, and tens of seconds on an async runtime thread is the whole UI.
 */
async exportGeneration(request: ExportRequest) : Promise<Result<ExportOutcome, ExportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_generation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens a bake and hands back the frames to treat.
 * 
 * The webview does the rendering, because the shader that drew the preview is
 * the shader that has to draw the export — one program, so the file cannot
 * disagree with what was on screen. What this side owns is the decode, the
 * scratch folder and the encode.
 * 
 * Blocking: decoding a five-second clip to PNGs is seconds of ffmpeg.
 */
async beginBake(sessionId: string, projectId: string, generationId: string, size: ExportSize) : Promise<Result<BakeSession, ExportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_bake", { sessionId, projectId, generationId, size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One treated frame, numbered by the caller so the sequence keeps its order.
 */
async writeBakedFrame(sessionId: string, index: number, png: number[]) : Promise<Result<null, ExportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_baked_frame", { sessionId, index, png }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Encodes the deliverables from the treated frames, then clears the scratch.
 * 
 * The frames are already at the export resolution, so nothing here scales them
 * again — that is what `Input::Treated*` says, and it is why turning a
 * treatment on cannot change the size of the file that ships.
 */
async finishBake(sessionId: string, fps: number | null, request: ExportRequest) : Promise<Result<ExportOutcome, ExportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finish_bake", { sessionId, fps, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The user changed their mind, or something went wrong up there.
 */
async cancelBake(sessionId: string) : Promise<Result<null, ExportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_bake", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Highest onboarding version the user has been walked through (PRD §7).
 * `0` means "never onboarded", which is also what a preferences file
 * written before this field existed deserialises to.
 */
onboarding_version?: number; 
/**
 * Where the last export landed (PRD §11 — genuinely app-wide, like the
 * concurrency limit, because an export folder is a place on this machine
 * rather than a property of a project).
 * 
 * `None` until somebody exports something. Remembered rather than
 * defaulted to Downloads, because the folder that matters is the one the
 * user picked last time — usually a repo's `public/` — and re-picking it
 * on every export is the friction this field exists to remove.
 */
export_directory?: string | null; 
/**
 * How far cost reconciliation has successfully read fal's billing events,
 * in milliseconds since the epoch (ADR 0003).
 * 
 * Here rather than in the SQLite index because the index is a cache whose
 * whole premise is that deleting it costs nothing, and this is the one
 * fact about the library that is not re-derivable from disk. It stretches
 * what a "preference" is; a third persistence mechanism for one number
 * would have been a worse trade.
 * 
 * `None` means nothing has ever been reconciled, which is also what a
 * preferences file written before this field existed reads as — and the
 * first pass then covers the whole 90 days fal will answer for, rather
 * than the 24 hours its API defaults to.
 * 
 * Only ever moved forward by a pass that *completed*. A failed one leaves
 * it exactly where it was, so the span it could not read is read again.
 */
reconciled_through?: number | null }
/**
 * A bake in progress, as the webview sees it.
 */
export type BakeSession = { id: string; 
/**
 * Absolute paths to the frames to treat, in order, ready for the asset
 * protocol. One entry for a still.
 */
frames: string[]; 
/**
 * The size the shader must render at — the size these will ship at.
 */
width: number; height: number; 
/**
 * Output pixels per look pixel, so the pattern comes out the size it was
 * dialled in at rather than the size the grid happens to be (#58).
 * 
 * 1 at [`ExportSize::Web`], 2 at `Double`, and whatever the source's own
 * width is worth at `Native`. The shader divides its pattern coordinates by
 * this, which is what makes a bigger export the same look with harder edges
 * instead of a finer screen nobody asked for.
 */
scale: number; 
/**
 * The clip's own rate, so the re-encode does not re-time it. `null` for a
 * still, which has no time axis.
 */
fps: number | null }
/**
 * What fal charged for one request.
 * 
 * Two fields out of the eleven the endpoint returns. The rest — the endpoint
 * id, the discount breakdown, the auth method — describe a request we already
 * have a recipe for; this exists to answer "what did that actually cost", and
 * carrying more would be a second, worse copy of the manifest.
 */
export type BillingCharge = { 
/**
 * fal's own id for the call — the only thing a generation can be joined
 * on, which is why it is persisted at collection (ADR 0003).
 */
requestId: string; 
/**
 * `cost_total`, in USD. fal bills in dollars wherever the account is.
 */
costUsd: number }
/**
 * The result of a cleanup, so the UI can say what it actually did rather than
 * "done".
 */
export type CleanupOutcome = { removedCount: number; freedBytes: number }
/**
 * What one CPU render was asked for.
 * 
 * The **inks are resolved before they get here**, darkest first: a duotone
 * arrives as a ramp between its two colours and a palette reduction arrives as
 * the project's own entries. Which colours a look uses is a question about the
 * look and the project, and this module's business is where the levels sit and
 * how the error moves.
 */
export type CpuEffect = { 
/**
 * `#RRGGBB`, darkest first, at least two.
 */
inks: string[]; kernel: DiffusionKernel; 
/**
 * Whether the levels sit where the inks' luminances actually are.
 * 
 * `false` spaces them evenly across the range, which is the
 * higher-contrast reading — and what #52 measured losing up to 0.22 of
 * mean linear luminance on Studio's four inks, because both interior steps
 * land in the one gap that palette has no ink for. Inert on a ramp, whose
 * luminances are already evenly spaced, which is why a duotone never has
 * to answer this question.
 */
paletteShaped: boolean }
/**
 * Which diffusion. The ordered screens live in the shaders, not here.
 */
export type DiffusionKernel = "floydSteinberg" | "atkinson"
/**
 * Why a CPU render produced nothing.
 */
export type EffectError = 
/**
 * The candidate has no file, or the file is not on disk.
 */
{ reason: "noAsset" } | 
/**
 * The bytes are not a picture this build can decode.
 */
{ reason: "undecodable"; detail: string } | 
/**
 * The treatment names fewer than two inks, or a colour that is not one.
 */
{ reason: "unusableInks" } | 
/**
 * The PNG could not be written back.
 */
{ reason: "encodeFailed"; detail: string }
/**
 * Why an export produced nothing.
 * 
 * A reason rather than a sentence, so the refusal can be said in the user's
 * own language (PRD §10.4) — the same shape `ImportError` takes for the same
 * reason. `EncodeFailed` carries a detail because ffmpeg's own last words are
 * the only thing that distinguishes a codec this build lacks from a disk that
 * filled up, and neither is something we can phrase in advance.
 */
export type ExportError = 
/**
 * No ffmpeg on this machine. The one error with an action attached.
 */
{ reason: "ffmpegMissing" } | 
/**
 * The candidate has no file — a paid result that never landed, or a
 * generation the manifest knows about and the assets folder does not.
 */
{ reason: "noAsset" } | 
/**
 * An MP4 or WebM was asked of a still. A styled still exports its poster.
 */
{ reason: "notAClip" } | 
/**
 * Every format was switched off.
 */
{ reason: "nothingRequested" } | { reason: "destinationUnusable"; message: string } | { reason: "encodeFailed"; deliverable: string; detail: string }
/**
 * What it produced.
 */
export type ExportOutcome = { 
/**
 * File names, not paths — they all landed in the destination that was
 * asked for, and the frontend already knows where that was.
 */
files: string[] }
/**
 * What one export was asked for.
 */
export type ExportRequest = { projectId: string; generationId: string; 
/**
 * Absolute, and chosen by the user through the system picker — remembered
 * in preferences between runs (PRD §11).
 */
destination: string; 
/**
 * What the files are called, before the extension. The frontend builds it
 * from the project and candidate names, because those are its own; this
 * side filters it into something a file can be called.
 */
baseName: string; mp4: boolean; webm: boolean; poster: boolean; 
/**
 * PRD §4.5's ping-pong. Ignored on a still, which has no time axis.
 */
rewind: boolean; 
/**
 * How big to deliver (#58). Anything above the web width is only honoured
 * where a treatment is being baked — see `ExportSize::untreated`.
 */
size: ExportSize }
/**
 * How big a deliverable ships (#58).
 * 
 * A treated export is the one case where more pixels are worth paying for, and
 * the reason is that a treatment is not photographic detail — it is a pattern
 * generated at the output grid. A dither drawn at 3840 has edges exactly one
 * output pixel hard whatever the picture underneath was; the upscaled photo
 * only has to supply tone, and a two-ink quantiser throws away most of the
 * tonal precision anyway. So the pattern stays sharp where a plain upscale
 * would just be a bigger blur.
 * 
 * **Every size is the same look.** The pattern is scaled with the export
 * ([`pattern_scale`](ExportSize::pattern_scale)), so `Double` is the picture the preview showed with harder
 * edges rather than a finer screen — which is what keeps the preview honest at
 * one size instead of needing to follow this choice around the app. It is also
 * what makes the MP4 better rather than merely bigger: a cell several output
 * pixels across survives the 4:2:0 chroma that ruins a one-pixel one.
 */
export type ExportSize = 
/**
 * [`MAX_WEB_WIDTH`], and what every export was before this existed.
 */
"web" | 
/**
 * The candidate's own size, uncapped — the pixels the model actually
 * returned, rather than the ones left after the web cap.
 */
"native" | 
/**
 * Twice the web width. Offered only where a treatment is being baked:
 * upscaling a clean plate is bytes with nothing in them.
 */
"double"
/**
 * What the frontend needs to decide whether export is offerable.
 * 
 * A struct rather than `Option<Ffmpeg>` because "not installed" is a state the
 * panel renders rather than an absence it ignores — it carries an install
 * prompt and a re-check button (PRD §8).
 */
export type FfmpegStatus = { available: boolean; path: string | null; version: string | null }
/**
 * A failure, as it crosses to the frontend.
 */
export type GenerationError = { reason: GenerationErrorReason; 
/**
 * Text fal supplied about this specific failure, when there was any.
 */
detail: string | null; 
/**
 * HTTP status, for `Unexpected`.
 */
status: number | null; 
/**
 * Which input-image problem it was, when `reason` is `InputImageUnusable`.
 */
inputImage: InputImageProblem | null }
/**
 * Why a generation did not produce an image.
 * 
 * A reason rather than a sentence: the sentence belongs in the locale files,
 * and the frontend is the only place that knows what language to say it in.
 * Same shape as `KeyCheck` in `api_key.rs` — unit enum plus optional detail —
 * so the frontend switches on one field.
 */
export type GenerationErrorReason = 
/**
 * Nothing was typed.
 */
"emptyPrompt" | 
/**
 * The stage had no usable input image (#28) — none was named, the file is
 * not on disk, or it is too large to inline. `input_image` says which.
 * 
 * A reason of its own rather than a `RequestRejected`, because fal never
 * saw this one: it is refused here, before the key is fetched and before
 * anything is charged. The Nano Banana edit endpoints do not require their
 * image field, so the alternative is a paid text-to-image nobody asked for.
 */
"inputImageUnusable" | 
/**
 * No key in the keychain — Settings first.
 */
"noApiKey" | 
/**
 * fal refused the key.
 */
"keyRejected" | 
/**
 * fal refused the request itself; `detail` says why.
 */
"requestRejected" | 
/**
 * Too many requests on this key.
 */
"rateLimited" | 
/**
 * The call never reached fal.
 */
"offline" | 
/**
 * The input image could not be put where fal could fetch it (#50).
 * 
 * Its own reason rather than an `Offline` or a `RequestRejected`, because
 * it is the one failure that happens *before* the queue is ever asked and
 * is therefore free: nothing has been submitted and nothing charged, and a
 * retry costs the user an upload rather than a generation.
 */
"uploadFailed" | 
/**
 * fal reported the job itself as failed.
 */
"jobFailed" | 
/**
 * We stopped waiting. The job may still finish on fal's side.
 */
"gaveUpWaiting" | 
/**
 * The image arrived but could not be written to disk.
 */
"couldNotSave" | 
/**
 * Anything else, with the status attached.
 */
"unexpected"
/**
 * Progress event payload. Emitted on every poll so the UI can say something
 * truthful while waiting.
 */
export type GenerationProgress = { requestId: string; projectId: string; generationId: string; status: QueueStatus; 
/**
 * Position in fal's queue, when it tells us.
 */
queuePosition: number | null; elapsedMs: number }
/**
 * Which image goes where, as the frontend names it.
 * 
 * The generation id rather than a path or bytes: the frontend knows *which
 * candidate* the stage is working from and nothing about the folder, and the
 * field name and shape are the registry's answer (PRD §5) rather than
 * something Rust should hold a second copy of.
 * 
 * One of these per *field*, not per image — a loop names the same generation
 * twice, under `imageParam` and under `endFrameParam` (#30).
 */
export type ImageInput = { generationId: string; 
/**
 * The model's own field name, from the registry's `imageParam` or
 * `endFrameParam`.
 */
param: string; shape: ImageParamShape }
/**
 * How a model's image field is shaped — the one thing knowing its *name* does
 * not tell you.
 * 
 * The style stage splits on this: the FLUX family takes a single `image_url`
 * string, Qwen and Nano Banana take an `image_urls` **array**. A string where an
 * array is required is a 422 at the paid step with no visual signal that the
 * parameter shape, rather than the prompt, was the problem.
 */
export type ImageParamShape = "url" | "urlArray"
/**
 * A refusal, as it crosses to the frontend.
 */
export type ImportError = { reason: ImportErrorReason; 
/**
 * Something specific about this file — the format we actually found, or
 * the size it actually was. Appended to the sentence, never instead of it.
 */
detail: string | null; 
/**
 * The ceiling, in bytes, so the message can name it without the frontend
 * keeping its own copy of a number Rust enforces.
 */
maxBytes: number }
/**
 * Why an image could not be brought in.
 * 
 * A reason rather than a sentence, matching `GenerationError` in
 * `jobs/fal.rs`: the words belong in the locale files, because the frontend
 * is the only side that knows what language to say them in (PRD §10.4).
 */
export type ImportErrorReason = 
/**
 * Nothing at that path, or it is not a file.
 */
"notFound" | 
/**
 * The file is there but could not be read.
 */
"unreadable" | 
/**
 * Not a PNG, JPEG or WebP, whatever the extension claims.
 */
"unsupportedFormat" | 
/**
 * Over `MAX_IMAGE_BYTES`.
 */
"tooLarge" | 
/**
 * The magic bytes matched but the header did not parse — a truncated or
 * corrupt file, which we would rather name now than hand to a model.
 */
"unreadableImage" | 
/**
 * The bytes were fine; writing them into the project was not.
 */
"couldNotSave"
/**
 * What landed in the project folder.
 * 
 * The dimensions come back because the aspect ratio has to be checked against
 * the project's locked one (PRD §4.4) *before* the upload is recorded, and the
 * frontend cannot read a local file's header itself.
 */
export type ImportedImage = { 
/**
 * A bare file name inside the project's `assets` folder, exactly as a
 * generated asset is — never a path.
 */
assetName: string; width: number; height: number }
/**
 * What was wrong with a stage's input image (#28).
 * 
 * A code, plus the numbers the sentence needs, rather than the sentence: this
 * refusal is ours rather than fal's — it happens before the request exists — so
 * unlike `detail` there is nobody to quote, and an English sentence built here
 * is one the user's locale can never translate (PRD §10.4). The frontend maps
 * each code to a key in `locales/`. Technical particulars stay on this side, in
 * the log, per `docs/developer/error-handling.md`.
 */
export type InputImageProblem = 
/**
 * No input generation was named at all — a restyle with nothing to restyle.
 */
{ code: "noneNamed" } | 
/**
 * The generation is named but has no file in the project's assets folder.
 */
{ code: "notOnDisk" } | 
/**
 * The file is there and could not be read, or holds nothing.
 */
{ code: "unreadable" } | 
/**
 * Not a PNG, JPEG or WebP, whatever its extension claims.
 */
{ code: "unsupportedFormat" } | 
/**
 * Over the ceiling on an inlined image, in bytes.
 */
{ code: "tooLarge"; bytes: number; limit: number } | 
/**
 * The registry named no field to put the image in.
 */
{ code: "noField" }
/**
 * A job as the frontend sees it: enough to show it, enough to record it in
 * the manifest once it finishes. The queue URLs stay in this module — they
 * are how *we* talk to fal, not something the webview has any use for.
 */
export type Job = { requestId: string; projectId: string; 
/**
 * Minted before submit, because the saved file is named after it.
 */
generationId: string; stage: string; 
/**
 * The recipe frozen at submit — opaque here, validated in TypeScript.
 * 
 * Copied rather than re-read from the draft, because by the time a
 * resumed job lands the draft may say something else entirely, and a
 * generation has to carry the recipe that actually produced it (PRD §1).
 */
recipe: JsonValue; status: JobStatus; modelId: string; 
/**
 * The seed fal used, once it has told us. `f64` because that is what a JS
 * number is — see `ProjectSummary`.
 */
seed: number | null; 
/**
 * The file, named relative to the project's assets folder.
 */
asset: string | null; submittedAt: number }
/**
 * How a job stopped being in flight.
 */
export type JobOutcome = 
/**
 * Finished, saved, and waiting to be written into the manifest.
 */
"completed" | 
/**
 * fal, the network or the disk said no. Off the books.
 */
"failed" | 
/**
 * The user asked us to stop. Off the books, and no promise of a refund.
 */
"cancelled" | 
/**
 * We stopped watching, but the job is still on the books and the next
 * launch resumes it.
 */
"abandoned"
/**
 * A job settled. Carries the ids rather than the result: the result is in the
 * store, and reading it from there is what makes a listener that missed the
 * event — because the app was not running — behave identically to one that
 * caught it.
 */
export type JobSettled = { requestId: string; projectId: string; generationId: string; outcome: JobOutcome; 
/**
 * Present for `Failed` and `Abandoned` — the frontend chooses the words.
 */
error: GenerationError | null }
/**
 * Where a job has got to, as far as this app is concerned.
 * 
 * A job that failed or was cancelled is removed rather than tombstoned:
 * nothing downstream can do anything with it, and the event that reports it is
 * what the UI reacts to.
 */
export type JobStatus = 
/**
 * Submitted, charged, and being watched right now.
 */
"running" | 
/**
 * On the books, but nobody is watching it this session — we waited longer
 * than one run of the app is willing to, or could not file the result.
 * 
 * Distinct from `Running` so the UI stops claiming to be waiting for
 * something nothing is waiting for. The next launch resumes it, which is
 * the whole reason it is not simply deleted.
 */
"stalled" | 
/**
 * Finished, with the file on disk, waiting for the manifest to record it.
 */
"completed"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Result of a validation attempt. Never contains the key itself.
 */
export type KeyCheck = { outcome: KeyCheckOutcome; 
/**
 * Account balance in USD, when the endpoint returned one. Doubles as a
 * low-funds signal before expensive jobs.
 */
balance: number | null; 
/**
 * HTTP status, for `Unexpected` only.
 */
status: number | null }
/**
 * What a validation attempt established. `Rejected` (the key is bad) and
 * `Unreachable` (we never got an answer) are deliberately separate: only the
 * first means the user needs to paste a different key.
 */
export type KeyCheckOutcome = 
/**
 * The key works.
 */
"valid" | 
/**
 * The key was refused — wrong, revoked or malformed.
 */
"rejected" | 
/**
 * No key is stored.
 */
"missing" | 
/**
 * The check never completed — offline, DNS failure, timeout.
 */
"unreachable" | 
/**
 * The endpoint answered something we don't recognise.
 */
"unexpected"
/**
 * A loaded project: the manifest, and where it came from.
 */
export type ProjectRecord = { directory: string; 
/**
 * Opaque here, validated in TypeScript. See the module comment.
 */
manifest: JsonValue }
/**
 * One row of the project list. Cheap enough to hold for every project, which
 * is the point of having an index at all (PRD §3.2).
 */
export type ProjectSummary = { id: string; name: string; aspect: string; 
/**
 * Milliseconds since the epoch. `f64` because that is what a JS number is
 * — an `i64` would cross the boundary as a string and buy nothing.
 */
createdAt: number; updatedAt: number; generationCount: number; 
/**
 * Where the manifest was found. Not stored in the manifest: a copied
 * folder must not insist it still lives where it was copied from.
 */
directory: string; 
/**
 * When this project last actually produced something — the newest
 * generation's creation time, falling back to the project's own.
 * 
 * Deliberately **not** `updated_at` (ADR 0004). The overview is ordered by
 * this, and renaming a project writes the manifest: sorting on the file's
 * timestamp would put a rename at the front of a grid whose whole subject
 * is work.
 */
latestActivityAt: number; 
/**
 * The card's picture, as a bare name inside `assets` — never a path, for
 * the reason a generation's asset is not one (PRD §3.2).
 * 
 * `None` while a project has nothing to show, or while a clip is waiting
 * for the webview to draw its poster.
 */
thumbnail: string | null; 
/**
 * The generation's own file, which the card's thumbnail was made from.
 * 
 * Carried because a card with no poster and a video here is precisely the
 * case the webview has to capture a frame from (ADR 0004).
 */
thumbnailAsset: string | null; 
/**
 * Whether that file is a clip — a card shows a play affordance rather than
 * an autoplaying element (ADR 0004).
 */
thumbnailIsVideo: boolean; 
/**
 * What the project has cost, in USD, as far as anything can tell.
 * 
 * Per generation, fal's confirmed charge where there is one and the
 * estimate stamped at collection where there is not (ADR 0003). Never a
 * mix of both for the same candidate: an `actualCostUsd` *replaces* its
 * estimate rather than being added to it.
 */
costUsd: number; 
/**
 * Generations carrying no cost at all — token-priced models never
 * reconciled, and anything recorded before costs were stamped. Named
 * rather than folded into the sum, so "unknown" and "free" never look the
 * same (ADR 0003).
 */
uncostedCount: number; 
/**
 * Generations whose cost is fal's own figure rather than our estimate.
 * 
 * The whole reason the sum can ever drop its tilde: a total is exact only
 * when this equals `generation_count` (ADR 0003). Counted here rather than
 * worked out on the card, because the overview must not open a manifest to
 * draw a grid.
 */
reconciledCount: number }
/**
 * What a project costs on disk, and how much of that nothing refers to
 * (PRD §10.3 — the visible pressure valve).
 */
export type ProjectUsage = { totalBytes: number; assetCount: number; 
/**
 * Files in `assets` no generation refers to.
 */
unusedBytes: number; unusedCount: number }
/**
 * Where a submitted job has got to.
 */
export type QueueStatus = "queued" | "running" | "completed"
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Everything needed to put one generation on the queue.
 * 
 * One struct rather than eight parameters: the list only grows as models gain
 * controls (#25), and a positional call of that length is a bug waiting for
 * two arguments of the same type to swap places.
 */
export type StartRequest = { projectId: string; generationId: string; stage: string; 
/**
 * The draft, frozen. Opaque — see `jobs::store`.
 */
recipe: JsonValue; prompt: string; 
/**
 * Which endpoint to call. Checked against the capability registry on the
 * TypeScript side before it is sent (PRD §5 — no arbitrary model ids) and
 * checked for URL safety here, because Rust is the side that spends.
 */
modelId: string; 
/**
 * The rest of the request body, keyed by the model's own field names and
 * built by the registry. Opaque here on purpose: knowing that Luma spells
 * duration `"5s"` requires the capability table, and there is one of
 * those.
 */
params: JsonValue; 
/**
 * Which generation's image this run consumes, and the field it goes in
 * (#28). Empty on a stage that takes no input image.
 * 
 * A generation id rather than the bytes: the image is read and encoded on
 * this side, so a hero-size payload never crosses the IPC boundary, and the
 * webview never has to be handed a path into the project folder.
 * 
 * A list because a looping animate run names the same still twice — once
 * as the first frame, once as the last (#30, PRD §4.5).
 */
imageInputs: ImageInput[] }
/**
 * What the caller gets back: a job that is now on the books, not a result.
 */
export type SubmittedJob = { requestId: string; generationId: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
