// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a key is stored. Local only — no network, no key returned.
 */
async hasFalApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates a pasted key and stores it in the keychain if it works.
 * 
 * A key that fails validation is not stored, so a saved key is always one that
 * worked at least once. Saving over an existing key replaces it.
 */
async saveFalApiKey(key: string) : Promise<Result<KeyCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_fal_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-validates the stored key against the live API.
 */
async checkFalApiKey() : Promise<Result<KeyCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the stored key. Succeeds when there was nothing to remove.
 */
async clearFalApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Submits one generation and returns as soon as it is on the books.
 * 
 * The generation id is minted by the caller and passed in rather than
 * returned: the file is named after it, so the manifest and the folder agree
 * without anyone having to reconcile them afterwards.
 * 
 * `recipe` is the draft frozen at submit, stored opaquely and handed back when
 * the job is collected. It travels with the job because a resumed job lands
 * in a session whose draft may say something else entirely, and a generation
 * has to carry the recipe that produced it (PRD §1).
 * 
 * `pinned_seed` is the seed the recipe asked for, if it asked for one
 * (PRD §4.3). Passing it is what makes "same seed, one changed fragment" a
 * real comparison rather than an approximate one.
 */
async generateImage(request: StartRequest) : Promise<Result<SubmittedJob, GenerationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_image", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What this project still has in flight — including anything a previous run
 * of the app submitted.
 */
async activeJobs(projectId: string) : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("active_jobs", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Finished jobs whose candidate is not in the manifest yet.
 */
async finishedJobs(projectId: string) : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finished_jobs", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Takes a collected job off the books.
 * 
 * Called after the manifest has been written, never before: the row is the
 * only record that a paid result exists, so dropping it first would turn a
 * badly timed crash into a lost generation.
 */
async claimJob(requestId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_job", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops a running job.
 * 
 * Cancelling stops us watching and asks fal to stop working. It does **not**
 * promise a refund — a job far enough along is charged regardless (PRD §3.3),
 * and the copy around this button says so.
 */
async cancelJob(requestId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_job", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The project list (PRD §10's left sidebar).
 * 
 * Reconciles first, so a deleted database, a project restored from a backup
 * and a folder copied in by hand all show up as simply "the projects".
 */
async listProjects() : Promise<Result<ProjectSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One project's manifest, as it is on disk.
 */
async loadProject(projectId: string) : Promise<Result<ProjectRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a manifest and updates its index row.
 * 
 * Also the create path: a project is created by saving one. There is no
 * separate "new project" on disk, so creation and every later edit take the
 * identical code path — including the atomic write.
 */
async saveProject(manifest: JsonValue) : Promise<Result<ProjectSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { manifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a project and everything in its folder.
 * 
 * The one thing here that removes anything without being asked twice, which
 * is why the caller is expected to have asked. PRD §10.3 keeps *candidates*,
 * not projects someone has explicitly thrown away.
 */
async deleteProject(projectId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the project costs on disk, and how much of it nothing points at
 * (PRD §10.3).
 */
async projectUsage(projectId: string) : Promise<Result<ProjectUsage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_usage", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the unreferenced assets, and only those. Deliberate, never
 * automatic — nothing is discarded until someone asks (PRD §10.3).
 */
async cleanupUnusedAssets(projectId: string) : Promise<Result<CleanupOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_unused_assets", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies an image the user already has into a project (#27).
 * 
 * The convergence point of the slice: what comes back is a file in the
 * project's `assets` folder named after its generation — the same artefact a
 * finished job produces — so nothing downstream has to know the pixels were
 * not generated.
 * 
 * Fails with a *reason* rather than a sentence, so the refusal can be said in
 * the user's own language (PRD §10.4), and fails before anything is recorded
 * so an unusable file never becomes a candidate.
 */
async importSourceImage(projectId: string, generationId: string, sourcePath: string) : Promise<Result<ImportedImage, ImportError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_source_image", { projectId, generationId, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
/**
 * The result of a cleanup, so the UI can say what it actually did rather than
 * "done".
 */
export type CleanupOutcome = { removedCount: number; freedBytes: number }
/**
 * A failure, as it crosses to the frontend.
 */
export type GenerationError = { reason: GenerationErrorReason; 
/**
 * Text fal supplied about this specific failure, when there was any.
 */
detail: string | null; 
/**
 * HTTP status, for `Unexpected`.
 */
status: number | null }
/**
 * Why a generation did not produce an image.
 * 
 * A reason rather than a sentence: the sentence belongs in the locale files,
 * and the frontend is the only place that knows what language to say it in.
 * Same shape as `KeyCheck` in `api_key.rs` — unit enum plus optional detail —
 * so the frontend switches on one field.
 */
export type GenerationErrorReason = 
/**
 * Nothing was typed.
 */
"emptyPrompt" | 
/**
 * No key in the keychain — Settings first.
 */
"noApiKey" | 
/**
 * fal refused the key.
 */
"keyRejected" | 
/**
 * fal refused the request itself; `detail` says why.
 */
"requestRejected" | 
/**
 * Too many requests on this key.
 */
"rateLimited" | 
/**
 * The call never reached fal.
 */
"offline" | 
/**
 * fal reported the job itself as failed.
 */
"jobFailed" | 
/**
 * We stopped waiting. The job may still finish on fal's side.
 */
"gaveUpWaiting" | 
/**
 * The image arrived but could not be written to disk.
 */
"couldNotSave" | 
/**
 * Anything else, with the status attached.
 */
"unexpected"
/**
 * Progress event payload. Emitted on every poll so the UI can say something
 * truthful while waiting.
 */
export type GenerationProgress = { requestId: string; projectId: string; generationId: string; status: QueueStatus; 
/**
 * Position in fal's queue, when it tells us.
 */
queuePosition: number | null; elapsedMs: number }
/**
 * A refusal, as it crosses to the frontend.
 */
export type ImportError = { reason: ImportErrorReason; 
/**
 * Something specific about this file — the format we actually found, or
 * the size it actually was. Appended to the sentence, never instead of it.
 */
detail: string | null; 
/**
 * The ceiling, in bytes, so the message can name it without the frontend
 * keeping its own copy of a number Rust enforces.
 */
maxBytes: number }
/**
 * Why an image could not be brought in.
 * 
 * A reason rather than a sentence, matching `GenerationError` in
 * `jobs/fal.rs`: the words belong in the locale files, because the frontend
 * is the only side that knows what language to say them in (PRD §10.4).
 */
export type ImportErrorReason = 
/**
 * Nothing at that path, or it is not a file.
 */
"notFound" | 
/**
 * The file is there but could not be read.
 */
"unreadable" | 
/**
 * Not a PNG, JPEG or WebP, whatever the extension claims.
 */
"unsupportedFormat" | 
/**
 * Over `MAX_IMAGE_BYTES`.
 */
"tooLarge" | 
/**
 * The magic bytes matched but the header did not parse — a truncated or
 * corrupt file, which we would rather name now than hand to a model.
 */
"unreadableImage" | 
/**
 * The bytes were fine; writing them into the project was not.
 */
"couldNotSave"
/**
 * What landed in the project folder.
 * 
 * The dimensions come back because the aspect ratio has to be checked against
 * the project's locked one (PRD §4.4) *before* the upload is recorded, and the
 * frontend cannot read a local file's header itself.
 */
export type ImportedImage = { 
/**
 * A bare file name inside the project's `assets` folder, exactly as a
 * generated asset is — never a path.
 */
assetName: string; width: number; height: number }
/**
 * A job as the frontend sees it: enough to show it, enough to record it in
 * the manifest once it finishes. The queue URLs stay in this module — they
 * are how *we* talk to fal, not something the webview has any use for.
 */
export type Job = { requestId: string; projectId: string; 
/**
 * Minted before submit, because the saved file is named after it.
 */
generationId: string; stage: string; 
/**
 * The recipe frozen at submit — opaque here, validated in TypeScript.
 * 
 * Copied rather than re-read from the draft, because by the time a
 * resumed job lands the draft may say something else entirely, and a
 * generation has to carry the recipe that actually produced it (PRD §1).
 */
recipe: JsonValue; status: JobStatus; modelId: string; 
/**
 * The seed fal used, once it has told us. `f64` because that is what a JS
 * number is — see `ProjectSummary`.
 */
seed: number | null; 
/**
 * The file, named relative to the project's assets folder.
 */
asset: string | null; submittedAt: number }
/**
 * How a job stopped being in flight.
 */
export type JobOutcome = 
/**
 * Finished, saved, and waiting to be written into the manifest.
 */
"completed" | 
/**
 * fal, the network or the disk said no. Off the books.
 */
"failed" | 
/**
 * The user asked us to stop. Off the books, and no promise of a refund.
 */
"cancelled" | 
/**
 * We stopped watching, but the job is still on the books and the next
 * launch resumes it.
 */
"abandoned"
/**
 * A job settled. Carries the ids rather than the result: the result is in the
 * store, and reading it from there is what makes a listener that missed the
 * event — because the app was not running — behave identically to one that
 * caught it.
 */
export type JobSettled = { requestId: string; projectId: string; generationId: string; outcome: JobOutcome; 
/**
 * Present for `Failed` and `Abandoned` — the frontend chooses the words.
 */
error: GenerationError | null }
/**
 * Where a job has got to, as far as this app is concerned.
 * 
 * A job that failed or was cancelled is removed rather than tombstoned:
 * nothing downstream can do anything with it, and the event that reports it is
 * what the UI reacts to.
 */
export type JobStatus = 
/**
 * Submitted, charged, and being watched right now.
 */
"running" | 
/**
 * On the books, but nobody is watching it this session — we waited longer
 * than one run of the app is willing to, or could not file the result.
 * 
 * Distinct from `Running` so the UI stops claiming to be waiting for
 * something nothing is waiting for. The next launch resumes it, which is
 * the whole reason it is not simply deleted.
 */
"stalled" | 
/**
 * Finished, with the file on disk, waiting for the manifest to record it.
 */
"completed"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Result of a validation attempt. Never contains the key itself.
 */
export type KeyCheck = { outcome: KeyCheckOutcome; 
/**
 * Account balance in USD, when the endpoint returned one. Doubles as a
 * low-funds signal before expensive jobs.
 */
balance: number | null; 
/**
 * HTTP status, for `Unexpected` only.
 */
status: number | null }
/**
 * What a validation attempt established. `Rejected` (the key is bad) and
 * `Unreachable` (we never got an answer) are deliberately separate: only the
 * first means the user needs to paste a different key.
 */
export type KeyCheckOutcome = 
/**
 * The key works.
 */
"valid" | 
/**
 * The key was refused — wrong, revoked or malformed.
 */
"rejected" | 
/**
 * No key is stored.
 */
"missing" | 
/**
 * The check never completed — offline, DNS failure, timeout.
 */
"unreachable" | 
/**
 * The endpoint answered something we don't recognise.
 */
"unexpected"
/**
 * A loaded project: the manifest, and where it came from.
 */
export type ProjectRecord = { directory: string; 
/**
 * Opaque here, validated in TypeScript. See the module comment.
 */
manifest: JsonValue }
/**
 * One row of the project list. Cheap enough to hold for every project, which
 * is the point of having an index at all (PRD §3.2).
 */
export type ProjectSummary = { id: string; name: string; aspect: string; 
/**
 * Milliseconds since the epoch. `f64` because that is what a JS number is
 * — an `i64` would cross the boundary as a string and buy nothing.
 */
createdAt: number; updatedAt: number; generationCount: number; 
/**
 * Where the manifest was found. Not stored in the manifest: a copied
 * folder must not insist it still lives where it was copied from.
 */
directory: string }
/**
 * What a project costs on disk, and how much of that nothing refers to
 * (PRD §10.3 — the visible pressure valve).
 */
export type ProjectUsage = { totalBytes: number; assetCount: number; 
/**
 * Files in `assets` no generation refers to.
 */
unusedBytes: number; unusedCount: number }
/**
 * Where a submitted job has got to.
 */
export type QueueStatus = "queued" | "running" | "completed"
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Everything needed to put one generation on the queue.
 * 
 * One struct rather than eight parameters: the list only grows as models gain
 * controls (#25), and a positional call of that length is a bug waiting for
 * two arguments of the same type to swap places.
 */
export type StartRequest = { projectId: string; generationId: string; stage: string; 
/**
 * The draft, frozen. Opaque — see `jobs::store`.
 */
recipe: JsonValue; prompt: string; 
/**
 * Which endpoint to call. Checked against the capability registry on the
 * TypeScript side before it is sent (PRD §5 — no arbitrary model ids) and
 * checked for URL safety here, because Rust is the side that spends.
 */
modelId: string; 
/**
 * The rest of the request body, keyed by the model's own field names and
 * built by the registry. Opaque here on purpose: knowing that Luma spells
 * duration `"5s"` requires the capability table, and there is one of
 * those.
 */
params: JsonValue }
/**
 * What the caller gets back: a job that is now on the books, not a result.
 */
export type SubmittedJob = { requestId: string; generationId: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
