// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a key is stored. Local only — no network, no key returned.
 */
async hasFalApiKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates a pasted key and stores it in the keychain if it works.
 * 
 * A key that fails validation is not stored, so a saved key is always one that
 * worked at least once. Saving over an existing key replaces it.
 */
async saveFalApiKey(key: string) : Promise<Result<KeyCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_fal_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-validates the stored key against the live API.
 */
async checkFalApiKey() : Promise<Result<KeyCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the stored key. Succeeds when there was nothing to remove.
 */
async clearFalApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_fal_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generates one image from a prompt, files it under the project, and reports
 * back.
 * 
 * The generation id is minted by the caller and passed in rather than
 * returned: the file is named after it, so the manifest and the folder agree
 * without anyone having to reconcile them afterwards.
 * 
 * `pinned_seed` is the seed the recipe asked for, if it asked for one
 * (PRD §4.3). Passing it is what makes "same seed, one changed fragment" a
 * real comparison rather than an approximate one.
 * 
 * Progress arrives as `generation-progress` events rather than as a return
 * value, because the interesting part happens while this is still running.
 */
async generateImage(projectId: string, generationId: string, prompt: string, aspect: string, pinnedSeed: number | null) : Promise<Result<Generation, GenerationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_image", { projectId, generationId, prompt, aspect, pinnedSeed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The project list (PRD §10's left sidebar).
 * 
 * Reconciles first, so a deleted database, a project restored from a backup
 * and a folder copied in by hand all show up as simply "the projects".
 */
async listProjects() : Promise<Result<ProjectSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One project's manifest, as it is on disk.
 */
async loadProject(projectId: string) : Promise<Result<ProjectRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a manifest and updates its index row.
 * 
 * Also the create path: a project is created by saving one. There is no
 * separate "new project" on disk, so creation and every later edit take the
 * identical code path — including the atomic write.
 */
async saveProject(manifest: JsonValue) : Promise<Result<ProjectSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { manifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a project and everything in its folder.
 * 
 * The one thing here that removes anything without being asked twice, which
 * is why the caller is expected to have asked. PRD §10.3 keeps *candidates*,
 * not projects someone has explicitly thrown away.
 */
async deleteProject(projectId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the project costs on disk, and how much of it nothing points at
 * (PRD §10.3).
 */
async projectUsage(projectId: string) : Promise<Result<ProjectUsage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_usage", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the unreferenced assets, and only those. Deliberate, never
 * automatic — nothing is discarded until someone asks (PRD §10.3).
 */
async cleanupUnusedAssets(projectId: string) : Promise<Result<CleanupOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_unused_assets", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
/**
 * The result of a cleanup, so the UI can say what it actually did rather than
 * "done".
 */
export type CleanupOutcome = { removedCount: number; freedBytes: number }
/**
 * A finished generation: the image, where it landed, and the recipe fragments
 * worth keeping. The seed is captured because it is what makes a generation
 * reproducible, and re-rolling costs money (PRD §4.3).
 */
export type Generation = { request_id: string; prompt: string; model_id: string; seed: string | null; 
/**
 * fal-hosted URL. Temporary — the file on disk is the durable copy.
 */
image_url: string; 
/**
 * The file name inside the project's `assets` folder. This is what the
 * manifest records, so it must survive the app-data folder moving.
 */
asset: string; 
/**
 * The same file, resolved. Transient — for display, never for storage.
 */
image_path: string; width: number | null; height: number | null }
/**
 * A failure, as it crosses to the frontend.
 */
export type GenerationError = { reason: GenerationErrorReason; 
/**
 * Text fal supplied about this specific failure, when there was any.
 */
detail: string | null; 
/**
 * HTTP status, for `Unexpected`.
 */
status: number | null }
/**
 * Why a generation did not produce an image.
 * 
 * A reason rather than a sentence: the sentence belongs in the locale files,
 * and the frontend is the only place that knows what language to say it in.
 * Same shape as `KeyCheck` in `api_key.rs` — unit enum plus optional detail —
 * so the frontend switches on one field.
 */
export type GenerationErrorReason = 
/**
 * Nothing was typed.
 */
"emptyPrompt" | 
/**
 * No key in the keychain — Settings first.
 */
"noApiKey" | 
/**
 * fal refused the key.
 */
"keyRejected" | 
/**
 * fal refused the request itself; `detail` says why.
 */
"requestRejected" | 
/**
 * Too many requests on this key.
 */
"rateLimited" | 
/**
 * The call never reached fal.
 */
"offline" | 
/**
 * fal reported the job itself as failed.
 */
"jobFailed" | 
/**
 * We stopped waiting. The job may still finish on fal's side.
 */
"gaveUpWaiting" | 
/**
 * The image arrived but could not be written to disk.
 */
"couldNotSave" | 
/**
 * Anything else, with the status attached.
 */
"unexpected"
/**
 * Progress event payload. Emitted on every poll so the UI can say something
 * truthful while waiting.
 */
export type GenerationProgress = { request_id: string; status: QueueStatus; 
/**
 * Position in fal's queue, when it tells us.
 */
queue_position: number | null; elapsed_ms: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Result of a validation attempt. Never contains the key itself.
 */
export type KeyCheck = { outcome: KeyCheckOutcome; 
/**
 * Account balance in USD, when the endpoint returned one. Doubles as a
 * low-funds signal before expensive jobs.
 */
balance: number | null; 
/**
 * HTTP status, for `Unexpected` only.
 */
status: number | null }
/**
 * What a validation attempt established. `Rejected` (the key is bad) and
 * `Unreachable` (we never got an answer) are deliberately separate: only the
 * first means the user needs to paste a different key.
 */
export type KeyCheckOutcome = 
/**
 * The key works.
 */
"valid" | 
/**
 * The key was refused — wrong, revoked or malformed.
 */
"rejected" | 
/**
 * No key is stored.
 */
"missing" | 
/**
 * The check never completed — offline, DNS failure, timeout.
 */
"unreachable" | 
/**
 * The endpoint answered something we don't recognise.
 */
"unexpected"
/**
 * A loaded project: the manifest, and where it came from.
 */
export type ProjectRecord = { directory: string; 
/**
 * Opaque here, validated in TypeScript. See the module comment.
 */
manifest: JsonValue }
/**
 * One row of the project list. Cheap enough to hold for every project, which
 * is the point of having an index at all (PRD §3.2).
 */
export type ProjectSummary = { id: string; name: string; aspect: string; 
/**
 * Milliseconds since the epoch. `f64` because that is what a JS number is
 * — an `i64` would cross the boundary as a string and buy nothing.
 */
createdAt: number; updatedAt: number; generationCount: number; 
/**
 * Where the manifest was found. Not stored in the manifest: a copied
 * folder must not insist it still lives where it was copied from.
 */
directory: string }
/**
 * What a project costs on disk, and how much of that nothing refers to
 * (PRD §10.3 — the visible pressure valve).
 */
export type ProjectUsage = { totalBytes: number; assetCount: number; 
/**
 * Files in `assets` no generation refers to.
 */
unusedBytes: number; unusedCount: number }
/**
 * Where a submitted job has got to.
 */
export type QueueStatus = "queued" | "running" | "completed"
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
