use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        api_key, export, jobs, notifications, preferences, presets, projects, quick_pane, recovery,
    };

    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            preferences::greet,
            api_key::has_fal_api_key,
            api_key::save_fal_api_key,
            api_key::check_fal_api_key,
            api_key::clear_fal_api_key,
            jobs::generate_image,
            jobs::active_jobs,
            jobs::finished_jobs,
            jobs::claim_job,
            jobs::cancel_job,
            projects::list_projects,
            projects::load_project,
            projects::save_project,
            projects::delete_project,
            projects::project_usage,
            projects::cleanup_unused_assets,
            projects::import_source_image,
            presets::user_presets_list,
            presets::user_preset_save,
            presets::user_preset_delete,
            presets::motion_presets_list,
            presets::motion_preset_save,
            presets::motion_preset_delete,
            presets::source_presets_list,
            presets::source_preset_save,
            presets::source_preset_delete,
            presets::user_palettes_list,
            presets::user_palette_save,
            presets::user_palette_delete,
            export::ffmpeg_status,
            export::recheck_ffmpeg,
            export::export_generation,
            preferences::load_preferences,
            preferences::save_preferences,
            notifications::send_native_notification,
            recovery::save_emergency_data,
            recovery::load_emergency_data,
            recovery::cleanup_old_recovery_files,
            quick_pane::show_quick_pane,
            quick_pane::dismiss_quick_pane,
            quick_pane::toggle_quick_pane,
            quick_pane::get_default_quick_pane_shortcut,
            quick_pane::update_quick_pane_shortcut,
        ])
        // Progress and settlement cross the boundary as emitted events rather
        // than return values, so no command signature mentions them — register
        // them explicitly or the frontend gets no type for what it listens to.
        .typ::<crate::jobs::fal::GenerationProgress>()
        .typ::<crate::jobs::runner::JobSettled>()
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                // A u64 doesn't fit a JS number. Seeds are echoed and stored,
                // never arithmetic, so a string crosses the boundary intact.
                .bigint(specta_typescript::BigIntExportBehavior::String)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
